### ISSUE TITLE
Issue with QR Code

### ISSUE THREAD

**Issue by jainpawan21** [heyAyushh/short10#2]
**1.** Generated QR code only contains the text part. It should contain the whole link so that one can use that link easily.
![Screenshot (118)](https://user-images.githubusercontent.com/39362422/80013154-118fb380-84ec-11ea-9029-04d23ed9dd57.png)
**2**. We can make the UI of this page more beautiful.
**3**. As this routes to another URL. Downloading this as png/jpeg on clicking QR code option will make this more user friendly.

**Comment by heyAyushh** [comment]
1. Fixed the code issue, It should be now proper link
2. & 3. I couldn't find a way to enable that in a single button, but that is surely i am looking for in upcoming releases

QR Code generator hence is a seperate module than this project. 

It is either 2 or 3

**Comment by heyAyushh** [comment]
Closing it for now.
